[project]
name = "zerotsuku-6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "regex>=2026.9.29",
    "tqdm>=4.70.1",
]

[project.scripts]
zerotsuku-6 = "zerotsuku_6:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
